export const ingredientsSelector = (state) =>state.ingr.arrIngredient;
export const ingredientsModalSelector = (state) =>state.modal.modalDetails;
export const noBunSelector = (state)  => state.constr.arrConstrIngr.filter((el) => el.type !== "bun");
export const bunSelector = (state)  => state.constr.arrConstrIngr.find((el) => el.type === "bun");
export const allOrderSelector = (state)  => state.constr.arrConstrIngr;
export const orderResponseSelector = (state)  => state.modalOrder.orderResponse;
export const isLoadingSelector = (state)  => (state.ingr.isLoading || state.modalOrder.isLoading || state.modalFeedOrder.isLoading);
export const currentTabSelector = (state)  => state.ingr.currentTab;
export const authSelector = (state)  => state.user.isAuth;
export const rstPswSelector = (state )  => state.user.isResetPsw;
export const userSelector = (state)  => state.user.user;
export const allFeedSelector = (state)  => state.feedAll.feed;
export const singleFeedOrderSelector = (state)  => state.modalFeedOrder.modalDetails;